# Generated by Django 4.2.15 on 2024-09-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_logintable_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='username',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
